// utils/data.js
const hotSeatQuestions = [
  // --- 🤣 LES MARRANTES & FAIL (Pour briser la glace) ---
  "Qui est le plus susceptible de mourir le premier dans un film d'horreur ?",
  "Qui est le plus susceptible de trébucher sur rien du tout ?",
  "Qui rit à ses propres blagues avant même de les finir ?",
  "Qui est le plus susceptible d'envoyer un message bourré à son ex ?",
  "Qui est le plus susceptible de commander une pizza alors qu'il a déjà dîné ?",
  "Qui a le plus de chances de finir dans une vidéo virale de chute ?",
  "Qui est le plus susceptible de s'endormir aux toilettes en soirée ?",
  "Qui est le plus susceptible de confondre deux célébrités ?",
  "Qui a le rire le plus étrange ou contagieux ?",
  "Qui est le plus susceptible de se faire arnaquer par un prince nigérian ?",
  "Qui est le plus susceptible de porter un pull à l'envers sans s'en rendre compte ?",
  "Qui est le plus susceptible de pleurer parce qu'il n'y a plus de fromage ?",
  "Qui est le plus susceptible de parler à un animal et d'attendre une réponse ?",
  "Qui ne sait absolument pas chuchoter ?",
  "Qui est le plus susceptible de se perdre avec un GPS ?",
  "Qui est le plus susceptible de casser son écran de téléphone le jour de l'achat ?",
  "Qui est le plus susceptible de faire pipi dans la piscine ?",
  "Qui est le plus susceptible d'oublier où il a garé sa voiture ?",
  "Qui est le plus susceptible de devenir un mème sur Internet ?",
  "Qui est le plus susceptible de mentir sur son âge ?",
  "Qui est le plus susceptible de rester coincé dans une balançoire pour enfants ?",
  "Qui est le plus susceptible de vomir dans un Uber ?",
  "Qui est le plus susceptible de se faire virer le premier jour de travail ?",
  "Qui est le plus susceptible de chanter les mauvaises paroles avec conviction ?",
  "Qui est le plus susceptible de mettre le feu à la cuisine en faisant des pâtes ?",
  "Qui a le plus de chances de survivre sur une île déserte... en mangeant les autres ?",
  "Qui est le plus susceptible d'adopter 10 chats ?",
  "Qui est le plus susceptible d'oublier de se laver les mains en sortant des toilettes ?",
  "Qui est le plus susceptible de liker une photo Instagram d'il y a 3 ans par erreur ?",
  "Qui est le plus susceptible d'arriver en retard à son propre mariage ?",
  "Qui est le plus susceptible de se disputer avec un robot téléphonique ?",
  "Qui est le plus susceptible de porter des chaussettes dépareillées ?",
  "Qui est le plus susceptible de raconter une histoire que personne n'écoute ?",
  "Qui a le plus de chances de finir au poste pour un malentendu ?",
  "Qui est le plus susceptible de voler un verre dans un bar ?",
  "Qui est le plus susceptible de demander à parler au manager ?",
  "Qui est le plus susceptible de danser sur une table ce soir ?",
  "Qui est le plus susceptible de se raser les sourcils par accident ?",
  "Qui est le plus susceptible de devenir un gourou de secte ?",
  "Qui est le plus susceptible de manger quelque chose de tombé par terre ?",

  // --- 🔥 LES COQUINES & SPICY (Pour faire monter la température) ---
  "Qui a le plus de chances d'avoir une sextape cachée quelque part ?",
  "Qui est le plus susceptible de coucher avec un collègue de travail ?",
  "Qui a l'historique de recherche Google le plus compromettant ?",
  "Qui est le plus susceptible d'avoir un compte OnlyFans secret ?",
  "Qui est le plus susceptible de faire l'amour dans un lieu public ?",
  "Qui est le plus bruyant au lit ?",
  "Qui est le plus susceptible de draguer le partenaire de quelqu'un d'autre ?",
  "Qui a le plus de jouets intimes chez lui ?",
  "Qui est le plus susceptible d'envoyer un 'nude' à la mauvaise personne ?",
  "Qui est le plus susceptible de coucher le premier soir ?",
  "Qui est le plus susceptible d'avoir un fantasme inavouable ?",
  "Qui a eu le plus de partenaires sexuels ici ?",
  "Qui est le plus susceptible de simuler au lit ?",
  "Qui est le plus susceptible d'essayer l'échangisme ?",
  "Qui est le plus susceptible d'embrasser quelqu'un du même sexe pour essayer ?",
  "Qui est le plus susceptible de se faire surprendre en plein acte par ses parents ?",
  "Qui est le plus susceptible de tomber amoureux de son plan cul ?",
  "Qui est le plus susceptible de coucher avec une célébrité s'il en a l'occasion ?",
  "Qui est le plus susceptible d'utiliser des menottes ?",
  "Qui est le plus susceptible d'avoir le 'body count' le plus bas ?",
  "Qui est le plus susceptible de sortir sans sous-vêtements ce soir ?",
  "Qui est le plus susceptible d'avoir déjà fait un plan à trois ?",
  "Qui a les goûts les plus bizarres en matière de porno ?",
  "Qui est le plus susceptible de revenir avec son ex toxique pour le sexe ?",
  "Qui est le plus susceptible de coucher avec quelqu'un juste pour son argent ?",
  "Qui est le plus susceptible de recevoir une plainte des voisins pour tapage nocturne (version sexe) ?",
  "Qui est le plus susceptible de flirter avec le barman pour des verres gratuits ?",
  "Qui est le plus susceptible d'avoir un fétichisme des pieds ?",
  "Qui est le plus susceptible de 'ghost' quelqu'un après avoir couché ?",
  "Qui est le plus susceptible de faire l'amour dans un avion ?",
  "Qui est le plus susceptible de s'inscrire sur une appli de rencontre ce soir ?",
  "Qui embrasse le mieux ?",
  "Qui est le plus susceptible de donner un faux numéro ?",
  "Qui est le plus susceptible d'avoir un sugar daddy / sugar mommy ?",
  "Qui est le plus susceptible de regarder du porno au travail ?",
  "Qui est le plus susceptible d'avoir une aventure d'un soir ce soir ?",
  "Qui est le plus susceptible de coucher avec le frère ou la sœur d'un ami ?",
  "Qui est le plus susceptible de se faire tatouer à un endroit intime ?",
  "Qui est le plus tactile ?",
  "Qui est le plus susceptible de proposer un strip-poker ?",

  // --- 👽 LES BIZARRES & ABSURDES (Pour les débats étranges) ---
  "Qui est le plus susceptible de croire que la Terre est plate ?",
  "Qui est le plus susceptible d'avoir été enlevé par des extraterrestres ?",
  "Qui est le plus susceptible de manger de la pâtée pour chat par curiosité ?",
  "Qui est le plus susceptible de devenir un ermite dans la forêt ?",
  "Qui a les phobies les plus ridicules ?",
  "Qui est le plus susceptible de ne pas se doucher pendant une semaine ?",
  "Qui est le plus susceptible de rejoindre une théorie du complot ?",
  "Qui est le plus susceptible de parler de sa digestion à table ?",
  "Qui est le plus susceptible de voler des bonbons à un enfant ?",
  "Qui est le plus susceptible d'avoir un ami imaginaire ?",
  "Qui est le plus susceptible de vendre ses organes au marché noir ?",
  "Qui est le plus susceptible de goûter son propre sang ?",
  "Qui est le plus susceptible d'avoir une double vie ?",
  "Qui est le plus susceptible de se déguiser en animal le week-end ?",
  "Qui est le plus susceptible de communiquer avec les esprits ?",
  "Qui est le plus susceptible de manger une araignée pour 10 euros ?",
  "Qui est le plus susceptible de garder ses rognures d'ongles ?",
  "Qui est le plus susceptible de vivre dans un van ?",
  "Qui est le plus susceptible de nommer son enfant 'Goku' ou 'Khaleesi' ?",
  "Qui est le plus susceptible de se faire cryogéniser ?",
  "Qui est le plus susceptible de savoir comment cacher un corps ?",
  "Qui est le plus susceptible d'avoir une collection d'objets glauques ?",
  "Qui est le plus susceptible de renifler ses propres vêtements sales ?",
  "Qui est le plus susceptible de croire aux vampires ?",
  "Qui est le plus susceptible de marcher pieds nus dans la rue ?",
  "Qui est le plus susceptible de manger la peau du kiwi ?",
  "Qui est le plus susceptible de dormir les yeux ouverts ?",
  "Qui est le plus susceptible de parler une langue qu'il a inventée ?",
  "Qui est le plus susceptible de se marier avec un objet ?",
  "Qui est le plus susceptible de survivre à une apocalypse zombie ?",

  // --- 🕵️ LES "CHERCHER" & INTROSPECTIVES (Pour juger gentiment) ---
  "Qui est le plus susceptible de devenir millionnaire avant 30 ans ?",
  "Qui est le plus susceptible de tout plaquer pour faire le tour du monde ?",
  "Qui est le plus susceptible de finir en prison ?",
  "Qui est le plus susceptible de gagner un prix Nobel ?",
  "Qui est le plus susceptible d'écrire une autobiographie ?",
  "Qui est le plus susceptible d'avoir une famille secrète ?",
  "Qui est le plus susceptible de pleurer devant une pub télé ?",
  "Qui est le plus susceptible de dépenser tout son salaire le premier jour ?",
  "Qui est le plus susceptible de ne jamais vouloir d'enfants ?",
  "Qui est le plus susceptible de devenir Président de la République ?",
  "Qui est le plus susceptible de pardonner une trahison ?",
  "Qui est le plus susceptible de garder un secret jusqu'à la tombe ?",
  "Qui est le plus susceptible d'avoir le meilleur goût musical ?",
  "Qui est le plus susceptible d'être le plus heureux dans la vie ?",
  "Qui est le plus susceptible de faire de la chirurgie esthétique ?",
  "Qui est le plus susceptible de devenir un moine bouddhiste ?",
  "Qui est le plus susceptible de mentir sur son CV ?",
  "Qui est le plus susceptible d'être un espion sous couverture ?",
  "Qui est le plus susceptible de changer de religion ?",
  "Qui est le plus susceptible d'avoir le pire caractère au réveil ?",
  "Qui est le plus susceptible de sauver tout le monde en cas d'incendie ?",
  "Qui est le plus susceptible de devenir influenceur TikTok ?",
  "Qui est le plus susceptible de vivre jusqu'à 100 ans ?",
  "Qui est le plus susceptible de se marier à Las Vegas sur un coup de tête ?",
  "Qui est le plus susceptible d'avoir le casier judiciaire le plus rempli ?",
  "Qui est le plus susceptible d'être secrètement un génie ?",
  "Qui est le plus susceptible de ruiner l'ambiance d'une soirée ?",
  "Qui est le plus susceptible d'être le plus généreux ?",
  "Qui est le plus susceptible de finir seul(e) avec 15 chiens ?",
  "Qui est le plus susceptible d'oublier l'anniversaire de son partenaire ?",
  "Qui est le plus susceptible d'avoir la vie la plus excitante ?",
  "Qui est le plus susceptible de faire une scène de jalousie en public ?",
  "Qui est le plus susceptible d'avoir le code moral le plus strict ?",
  "Qui est le plus susceptible de se faire tatouer le visage ?",
  "Qui est le plus susceptible d'être le 'maman/papa' du groupe ?",
  "Qui est le plus susceptible de réussir un crime parfait ?",
  "Qui est le plus susceptible de devenir une star de télé-réalité ?",
  "Qui est le plus susceptible d'avoir peur du noir ?",
  "Qui est le plus susceptible d'avoir le plus gros ego ?",
  "Qui est le plus susceptible d'être le plus romantique ?",

  // --- 🍸 MIX ALÉATOIRE (Pour finir la soirée) ---
  "Qui est le plus susceptible de commander le plat le plus cher ?",
  "Qui est le plus susceptible de critiquer la nourriture ?",
  "Qui est le plus susceptible de parler politique en soirée ?",
  "Qui est le plus susceptible de draguer le chauffeur de taxi ?",
  "Qui est le plus susceptible de se casser une dent en ouvrant une bouteille ?",
  "Qui est le plus susceptible de s'inscrire à une salle de sport et ne jamais y aller ?",
  "Qui est le plus susceptible de tricher aux jeux de société ?",
  "Qui est le plus susceptible d'avoir peur des clowns ?",
  "Qui est le plus susceptible de porter un pyjama toute la journée ?",
  "Qui est le plus susceptible de ne pas rendre l'argent qu'on lui prête ?",
  "Qui est le plus susceptible d'avoir la pire photo de permis de conduire ?",
  "Qui est le plus susceptible de se faire attaquer par un oiseau ?",
  "Qui est le plus susceptible de pleurer en écoutant Adèle ?",
  "Qui est le plus susceptible d'avoir un faux compte Instagram pour espionner ?",
  "Qui est le plus susceptible de faire semblant d'être malade pour ne pas sortir ?",
  "Qui est le plus susceptible de voler les petits shampoings à l'hôtel ?",
  "Qui est le plus susceptible de ne jamais répondre aux messages ?",
  "Qui est le plus susceptible de faire un discours gênant ?",
  "Qui est le plus susceptible de se perdre dans un supermarché ?",
  "Qui est le plus susceptible de manger la part de pizza de quelqu'un d'autre ?",
  "Qui est le plus susceptible de ronfler le plus fort ?",
  "Qui est le plus susceptible d'avoir les pieds qui puent ?",
  "Qui est le plus susceptible de faire une blague au pire moment possible ?",
  "Qui est le plus susceptible de gagner Koh-Lanta ?",
  "Qui est le plus susceptible de ne pas comprendre les règles du jeu ?",
  "Qui est le plus susceptible de casser son verre ce soir ?",
  "Qui est le plus susceptible d'avoir le fou rire pendant un enterrement ?",
  "Qui est le plus susceptible de hacker le compte de son ex ?",
  "Qui est le plus susceptible de devenir vegan du jour au lendemain ?",
  "Qui est le plus susceptible de dépenser 1000€ dans des jeux vidéo ?"
];
const wordPairs = [
  ["Pizza", "Tarte"], ["Facebook", "Instagram"], ["Batman", "Superman"],
  ["Coca-Cola", "Pepsi"], ["McDonald's", "Burger King"], ["Chat", "Chien"],
  ["Paris", "Londres"], ["Plage", "Piscine"], ["Ski", "Snowboard"],
  ["Bière", "Vin"], ["Café", "Thé"], ["Netflix", "YouTube"],
  ["iPhone", "Samsung"], ["Chocolat", "Caramel"], ["Dentiste", "Médecin"],
  ["Bus", "Métro"], ["Guitare", "Piano"], ["Football", "Rugby"],
  ["Croissant", "Pain au chocolat"], ["Noël", "Nouvel An"],
  ["Mariage", "Anniversaire"], ["Livre", "Film"], ["Lunettes", "Lentilles"],
  ["Tatouage", "Piercing"], ["Fromage", "Beurre"], ["Champagne", "Prosecco"],
  ["TikTok", "Instagram Reels"], ["Uber", "Taxi"], ["Airbnb", "Hôtel"],
  ["Google", "Bing"], ["WhatsApp", "Messenger"], ["Mario", "Sonic"],
  ["Harry Potter", "Seigneur des Anneaux"], ["Star Wars", "Star Trek"],
  ["Stranger Things", "Black Mirror"], ["Spotify", "Apple Music"],
  ["Jean", "Pantalon"], ["Baskets", "Chaussures"], ["Sushi", "Maki"],
  ["Hamburger", "Hot-dog"], ["Crêpe", "Gaufre"], ["Glace", "Sorbet"],
  ["Mojito", "Caïpirinha"], ["Vodka", "Rhum"], ["Karaoké", "Blind test"],
  ["Poker", "Blackjack"], ["Monopoly", "Uno"], ["Escape Game", "Laser Game"],
  ["Camping", "Glamping"], ["Vélo", "Trottinette"], ["Avion", "Train"],
  ["Montagne", "Mer"], ["Été", "Printemps"], ["Lundi", "Mardi"],
  ["Matin", "Soir"], ["Douche", "Bain"], ["Canapé", "Fauteuil"],
  ["Coussin", "Oreiller"], ["Couverture", "Plaid"], ["Bougie", "Encens"], ["Zizi", "Couilles"], ["Carla", "Charlotte"]
];

// Si tu veux gérer la logique de roue côté serveur (optionnel mais propre)
// public/app.js - Segments par défaut LOCAL
// Note l'utilisation de {player} au singulier
let wheelSegments = [
  { color: '#e74c3c', name: 'Cul sec', gages: ['Tout le monde boit !', 'Cul sec pour {player}'], target: 'victim', count: 1 },
  { color: '#3498db', name: 'Vérité', gages: ['{player} doit raconter une honte', '{player} montre sa dernière photo'], target: 'victim', count: 0 },
  { color: '#f1c40f', name: 'Distribue', gages: ['{player} distribue 2 gorgées', '{player} distribue 5 gorgées'], target: 'victim', count: 0 },
  { color: '#2ecc71', name: 'Jeu', gages: ['Dans ma valise...', 'Action ou Vérité pour {player}'], target: 'victim', count: 0 },
  { color: '#9b59b6', name: 'Shot', gages: ['Shot pour {player} !', 'Les voisins de {player} boivent'], target: 'victim', count: 0 }
];

module.exports = { hotSeatQuestions, wordPairs, wheelSegments };